# Generated by Django 5.2.5 on 2025-10-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
