# Generated by Django 5.2.5 on 2025-10-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janela', '0004_produto_carrinho_itemcarrinho_carrinho_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_produtos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
